apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app
  labels:
    app.kubernetes.io/part-of: cloudsalaryhub
  annotations:
    app.kubernetes.io/description: "Shared application configuration for all microservices in the app namespace"
data:
  IDENTITY_SERVICE_URL: "http://identity-service:8001"
  SALARY_SERVICE_URL: "http://salary-submission-service:8002"
  SEARCH_SERVICE_URL: "http://search-service:8003"
  STATS_SERVICE_URL: "http://stat-service:8004"
  VOTE_SERVICE_URL: "http://vote-service:8005"

  POSTGRES_DB: "cloud-salary-hub"
  POSTGRES_HOST: "postgres.data.svc.cluster.local"
  POSTGRES_PORT: "5432"

  JWT_ALGORITHM: "HS256"
  JWT_EXPIRATION_MINUTES: "60"
