apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: app
  labels:
    app.kubernetes.io/name: identity-service
    app.kubernetes.io/part-of: cloudsalaryhub
    app.kubernetes.io/component: backend
  annotations:
    app.kubernetes.io/description: "ClusterIP service for identity-service"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: identity-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      protocol: TCP
