apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudsalaryhub-ingress
  namespace: cloudsalaryhub
spec:
  ingressClassName: nginx
  rules:
    - host: cloudsalaryhub.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: bff-service
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
