apiVersion: v1
kind: Namespace
metadata:
  name: cloudsalaryhub
  labels:
    app.kubernetes.io/part-of: cloudsalaryhub
  annotations:
    app.kubernetes.io/description: "CloudSalaryHub microservices namespace"
