apiVersion: v1
kind: Service
metadata:
  name: salary-submission-service
  namespace: cloudsalaryhub
  labels:
    app.kubernetes.io/name: salary-submission-service
    app.kubernetes.io/part-of: cloudsalaryhub
    app.kubernetes.io/component: backend
  annotations:
    app.kubernetes.io/description: "ClusterIP service for salary-submission-service"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: salary-submission-service
  ports:
    - name: http
      port: 8002
      targetPort: 8002
      protocol: TCP
