apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: cloudsalaryhub
  labels:
    app.kubernetes.io/name: vote-service
    app.kubernetes.io/part-of: cloudsalaryhub
    app.kubernetes.io/component: backend
  annotations:
    app.kubernetes.io/description: "ClusterIP service for vote-service"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vote-service
  ports:
    - name: http
      port: 8005
      targetPort: 8005
      protocol: TCP
